dist: bionic
language: python
python:
  - "2.7.15"
install:
  - sudo apt-get update
  - pip install subprocess32
  - pip install -Iv 'cython>0.22.0,<=0.23.4'
  - pip install -Iv 'numpy>=1.10.0,<1.11.0'
  - pip install -Iv 'pysam>0.9.0,<=0.9.2'
  - pip install https://github.com/timothyjamesbecker/FusorSV/releases/download/0.1.3-beta/fusorsv-0.1.3.tar.gz
script:
  - FusorSV.py -h
